-- SM-6: Community Translations
-- Allows users to submit, vote on, and verify translations for cards and song lyrics.

-- Community translations for cards and lyrics
create table skill_mode_translations (
  id uuid primary key default gen_random_uuid(),
  -- What is being translated
  card_id uuid references skill_mode_cards(id) on delete cascade,
  song_id uuid references skill_mode_songs(id) on delete cascade,
  lyric_line_index integer,             -- null for card translations, line index for lyrics
  -- Translation content
  source_text text not null,            -- original foreign text
  translated_text text not null,        -- community translation
  target_language text not null default 'en', -- language translated INTO
  notes text,                           -- translator's notes (grammar hints, context)
  -- Contributor
  translator_id uuid references profiles(id) on delete cascade not null,
  is_first_translator boolean default false, -- permanent credit badge
  is_ai_draft boolean default false,    -- generated by AI, not a human
  -- Verification
  status text not null default 'pending', -- 'pending' | 'verified' | 'rejected' | 'expert_verified'
  verified_by uuid references profiles(id) on delete set null,
  verified_at timestamptz,
  -- Voting aggregates (denormalised for perf)
  upvotes integer default 0,
  downvotes integer default 0,
  net_score integer generated always as (upvotes - downvotes) stored,
  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  -- Either card_id or song_id must be set
  constraint translation_target_check check (
    (card_id is not null and song_id is null) or
    (card_id is null and song_id is not null)
  )
);

-- Votes on translations
create table skill_mode_translation_votes (
  id uuid primary key default gen_random_uuid(),
  translation_id uuid references skill_mode_translations(id) on delete cascade not null,
  voter_id uuid references profiles(id) on delete cascade not null,
  vote smallint not null check (vote in (-1, 1)), -- -1 = downvote, 1 = upvote
  created_at timestamptz default now(),
  -- One vote per user per translation
  unique (translation_id, voter_id)
);

-- Translator trust scores (aggregated per user per language pair)
create table skill_mode_translator_stats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  target_language text not null default 'en',
  -- Trust metrics
  trust_score numeric default 0,        -- calculated: (verified_count * 10 + net_votes) / total_submissions
  total_submissions integer default 0,
  verified_count integer default 0,
  rejected_count integer default 0,
  total_net_votes integer default 0,     -- sum of net_score across all their translations
  -- Tier
  tier text default 'newcomer',         -- 'newcomer' | 'contributor' | 'trusted' | 'expert'
  is_native_speaker boolean default false,
  -- Timestamps
  first_translation_at timestamptz,
  updated_at timestamptz default now(),
  -- One stats row per user per target language
  unique (user_id, target_language)
);

-- RLS
alter table skill_mode_translations enable row level security;
alter table skill_mode_translation_votes enable row level security;
alter table skill_mode_translator_stats enable row level security;

-- Translations: anyone can read, authenticated users can insert own, translators can update own pending
create policy "Translations readable by all" on skill_mode_translations
  for select using (true);
create policy "Authenticated users can submit translations" on skill_mode_translations
  for insert with check (auth.uid() = translator_id);
create policy "Translators can update own pending translations" on skill_mode_translations
  for update using (auth.uid() = translator_id and status = 'pending');

-- Votes: anyone can read, authenticated users manage own votes
create policy "Votes readable by all" on skill_mode_translation_votes
  for select using (true);
create policy "Users can vote" on skill_mode_translation_votes
  for insert with check (auth.uid() = voter_id);
create policy "Users can change own vote" on skill_mode_translation_votes
  for update using (auth.uid() = voter_id);
create policy "Users can remove own vote" on skill_mode_translation_votes
  for delete using (auth.uid() = voter_id);

-- Translator stats: readable by all, users manage own
create policy "Translator stats readable by all" on skill_mode_translator_stats
  for select using (true);
create policy "Users manage own translator stats" on skill_mode_translator_stats
  for all using (auth.uid() = user_id);

-- Indexes
create index on skill_mode_translations (card_id, target_language, net_score desc);
create index on skill_mode_translations (song_id, lyric_line_index, target_language, net_score desc);
create index on skill_mode_translations (translator_id);
create index on skill_mode_translations (status);
create index on skill_mode_translation_votes (translation_id);
create index on skill_mode_translation_votes (voter_id);
create index on skill_mode_translator_stats (user_id, target_language);
create index on skill_mode_translator_stats (trust_score desc);

-- RPC: Cast a translation vote (upsert + update denormalised counts)
create or replace function cast_translation_vote(
  p_translation_id uuid,
  p_voter_id uuid,
  p_vote smallint
) returns void as $$
declare
  v_old_vote smallint;
begin
  -- Check for existing vote
  select vote into v_old_vote
  from skill_mode_translation_votes
  where translation_id = p_translation_id and voter_id = p_voter_id;

  if found then
    if v_old_vote = p_vote then
      -- Same vote = remove it
      delete from skill_mode_translation_votes
      where translation_id = p_translation_id and voter_id = p_voter_id;
      -- Update counts
      if p_vote = 1 then
        update skill_mode_translations set upvotes = upvotes - 1, updated_at = now()
        where id = p_translation_id;
      else
        update skill_mode_translations set downvotes = downvotes - 1, updated_at = now()
        where id = p_translation_id;
      end if;
    else
      -- Different vote = flip
      update skill_mode_translation_votes set vote = p_vote
      where translation_id = p_translation_id and voter_id = p_voter_id;
      if p_vote = 1 then
        update skill_mode_translations
        set upvotes = upvotes + 1, downvotes = downvotes - 1, updated_at = now()
        where id = p_translation_id;
      else
        update skill_mode_translations
        set upvotes = upvotes - 1, downvotes = downvotes + 1, updated_at = now()
        where id = p_translation_id;
      end if;
    end if;
  else
    -- New vote
    insert into skill_mode_translation_votes (translation_id, voter_id, vote)
    values (p_translation_id, p_voter_id, p_vote);
    if p_vote = 1 then
      update skill_mode_translations set upvotes = upvotes + 1, updated_at = now()
      where id = p_translation_id;
    else
      update skill_mode_translations set downvotes = downvotes + 1, updated_at = now()
      where id = p_translation_id;
    end if;
  end if;

  -- Auto-verify: if net_score >= 5 and status = 'pending', promote to 'verified'
  update skill_mode_translations
  set status = 'verified', verified_at = now()
  where id = p_translation_id and status = 'pending' and (upvotes - downvotes) >= 5;
end;
$$ language plpgsql security definer;
